version: '3.8'

services:
  python-server:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.python
    ports:
      - 8082:8082
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://kashyap:password@mongo:27017/bookstore  # Updated URI

  mongo:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kashyap
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - product-data:/data/db

  mongo-express:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.mongoexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=kashyap
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - 8081:8081
      
volumes:
  product-data:
    driver: local
