# Use the official MinIO image as the base image
FROM minio/minio:latest

ENV MINIO_ROOT_USER=kashyap
ENV MINIO_ROOT_PASSWORD=password

# 9000 for the API, 9001 for the console
EXPOSE 9000
EXPOSE 9001

ENTRYPOINT ["minio"]
CMD ["server", "/data", "--console-address", ":9001"]
