apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  type: ClusterIP  # You can change this to LoadBalancer if you need external access
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: minio
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: minio-console
  selector:
    app: minio


