apiVersion: v1
kind: Service
metadata:
  name: python-server-service
  labels:
    app: python-server
spec:
  type: LoadBalancer  # Use ClusterIP if you don't need external access
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: python-server
